[package]
name = "slackfm"
version = "0.1.0"
authors = ["James Forcier <csssuf@csssuf.net>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slack_api = "0.19"
